### ISSUE TITLE
[EPIC004_TKT001_vendor_routes] Attempting to get all vendors while unauthenticated crashes

### ISSUE THREAD

**Issue by CHEUNG-K-Jeffrey** [Code-the-Dream-School/gg-pac-team5-back#6]
Definitely crashes with 0fdb864d661b3b8a001de29b902dd7458535702d
```
GET /api/v1/vendors 500 8.637 ms - 1832
TypeError: Cannot read properties of undefined (reading 'split')
    at authenticationMiddleware (/Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/src/middleware/authentication.js:8:28)
    at newFn (/Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/node_modules/express/lib/router/index.js:328:13)
    at /Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/node_modules/express/lib/router/index.js:280:10)
    at /Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/node_modules/express-favicon/index.js:18:12
    at newFn (/Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/Users/jeffreycheung/Source Code/Mighty Heap Practicum Project/gg-pac-team5-back/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by SergeDot** [comment]
I believe this is due to the database being online. I am checking with Chase how to deal with that to make the code shareable
